### ISSUE TITLE
Address devtools console errors

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/built-with-workers#10]
@signalnerve would appreciate your help with these.

![image](https://user-images.githubusercontent.com/154613/68631872-67324f80-04ba-11ea-9c2f-3e0b4192f3f7.png)

**Comment by signalnerve** [comment]
> Re: lazy loading, can we instruct Gatsby to specify dimension attributes on the HTML based on a max width (e.g. width="100vw" height="100vh" [or, at runtime, the computed pixel value version of these if possible]) just to silence the warning? (The CSS would override to make it fluid.)

if you'd like me to, (i think) i can do that – can pass in some values to the `gatsby-image` pkg. fwiw this is a chrome-specific error and a bug report in chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1002455) so it feels like we're not doing anything wrong here!

> Re: same site cookie, Is this something we have control over in Cloudflare and/or Sanity?

nope, unfortunately :/
