### ISSUE TITLE
Planning: Moving landing page content to this repository

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/built-with-workers#15]
Per #9, we are exploring moving the landing page content into this codebase, which will serve as the new home for everything on `workers.cloudflare.com`. 

My early attempts at getting the content from that site (two pages) to load has been fairly successful: this is after about 20min of work.

<img width="1244" alt="Screen Shot 2019-11-14 at 1 31 53 PM" src="https://user-images.githubusercontent.com/922353/68889894-78aa7000-06e3-11ea-9cbf-7c4f0b0fb535.png">

There's a bunch of vendored CSS in this repository that is shared with the landing page – Adam and I have been discussing how to effectively move it _back_ into the landing page repo (or vendoring the assets appropriately so that it can be shared between them), but by merging that content into this repo, we're effectively putting off that problem for the immediate future, as this repo can become the definitive source for the CSS and the content for both sites.

Before we move ahead on this, we'll need to explore a couple additional things:

- The current Workers script for the landing page has a redirect set up to send all `/docs*` requests to the Workers docs (`developers.cloudflare.com/workers`). The code for that is [in `workers-site/index.js`](https://github.com/cloudflare/workers.cloudflare.com/blob/master/workers-site/index.js#L10). We should either move that into the script for this project, _or_ potentially compose a new script that just lives on `/docs*` and takes higher precedence over the script for this application. The benefit there would be that potentially we could show off this project as a pure JAMstack app using the default Workers Sites script ("It works with no additional config – look!").
- Building off of the last point, we're now in the GTM task territory of "We're open sourcing our landing page" – I'm +1 on this, but want to make sure everyone is in on that. This will have a similar effect to the docs, where we then need to be more discerning about open PRs that indicate new features, etc. Again, I'm also +1 after all of that, but it seems like something that needs #socializing :)

**Comment by adamschwartz** [comment]
https://github.com/cloudflare/built-with-workers/pull/100
