### ISSUE TITLE
List view images start out blurry even when cached

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/built-with-workers#50]
It’s subtle, but:

1. Navigate to https://built-with-workers.signalnerve.workers.dev/built-with
2. Click the first project
3. Hit browser back button

Observe that the list view images render blurry for at least 1 render frame, sometimes more.

**Comment by signalnerve** [comment]
@adamschwartz i've been testing this with network throttling and finding that the image doesn't seem to re-cache.... except one random time. i wonder if there's some sort of caching mechanism that expires and re-fetches the image? i can't even recreate again so not sure :( 

generally i find that in chrome/firefox my images are staying cached (even when jumping between projects) so i'd be curious to hear if you're still running into this, and if you're able to recreate it easily

**Comment by adamschwartz** [comment]
I can’t repro anymore. Caching seems to be working well now. 🤷‍♂️
