### ISSUE TITLE
Add `.live` property to Project schema

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/built-with-workers#62]
@signalnerve This came from a conversation @ashleygwilliams and I had earlier today. We felt like it would improve moderation ergonomics to have a `project.live` property (or `isLive`?—up to you) which we can use to filter projects from inclusion in collections on the homepage.

Currently, if you mark a project as a draft (to achieve a similar end goal), Sanity tells you that this will break the collections that project is a member of (which makes sense). So instead, if you were able to keep it "published" (as far as Sanity is concerned) but with the `live` flag turned off, we could still generate a `/built-with/projects/slug` page for it, but prevent it from showing on the homepage.

**Comment by signalnerve** [comment]
as discussed in our sync up today, this is happening because we have a concept of "feature" collections, which are due to be removed in #96. when this happens, collections will be completely curated and we won't need to hide projects from inclusion in them. will close this issue with that work
